#! /bin/bash


redocly build-docs ./docs/openapi.yaml --output ./docs/redoc-static.html 2>/dev/null

if [ $? -ne 0 ]; then
  echo "Redoc not generated."
else
  echo "Redoc generated."
fi

python openapi-yaml-to-html.py < ./docs/openapi.yaml > ./docs/swagger-doc.html 2>/dev/null

if [ $? -ne 0 ]; then
  echo "Swagger not generated."
else
  echo "Swagger generated."
fi
