# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--junit-xml=./unittests.xml",
    "--cov=./src",
    "--cov-report=term",
    "--cov-report=xml",
    "--cov-branch",
    "-p tests.plugins.env_vars",
]
python_files = [
    "tests.py",
    "test_*.py",
]
log_cli = true

# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = []
skip = ["venv/"]

# ==== PyLint ====
[tool.pylint.MASTER]
load-plugins = []

[tool.pylint.FORMAT]
max-line-length = 119

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "missing-docstring",
    "invalid-name",
]

[tool.pylint.DESIGN]
max-parents = 13

[tool.pylint.TYPECHECK]
generated-members = [
    "REQUEST",
    "acl_users",
    "aq_parent",
    "[a-zA-Z]+_set{1,2}",
    "save",
    "delete",
]
